context:
  name: jumanji
  version: 1.0.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/jumanji-${{ version }}.tar.gz
  sha256: cdbc0245deb2f72cfdaf3719793a484d26ac25b06f2bfaa0e8323a1d79fef8d2
  patches:
    - relax-matplotlib-pin.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - chex >=0.1.3
    - dm-env >=1.5
    - gym >=0.22.0
    - huggingface_hub
    - jax >=0.2.26
    - matplotlib-base
    - numpy
    - pillow >=9.0.0
    - typing_extensions >=4.0.0

tests:
  - python:
      imports:
        - jumanji
      pip_check: true

about:
  summary: A diverse suite of scalable reinforcement learning environments in JAX
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/instadeepai/jumanji/

extra:
  recipe-maintainers:
    - Tobias-Fischer
